# Generated by Django 3.0.6 on 2020-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile', models.ImageField(upload_to='images/profile/')),
                ('genres', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('directory_address', models.CharField(max_length=250)),
            ],
        ),
    ]
