# Generated by Django 3.0.6 on 2020-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangatitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitles',
            name='current_chapter',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
