# Generated by Django 3.0.6 on 2020-08-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangatitles', '0002_mangatitles_current_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitles',
            name='fav',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
