# Generated by Django 3.0.6 on 2020-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangatitles', '0003_mangatitles_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitles',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
