# Generated by Django 3.0.6 on 2020-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangatitles', '0004_mangatitles_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangatitles',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mangatitles',
            name='current_chapter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mangatitles',
            name='fav',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
