# Generated by Django 3.0.6 on 2020-09-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangatitles', '0005_auto_20200820_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangatitles',
            name='genres',
        ),
    ]
